# Generated by Django 5.0.6 on 2026-08-09 17:53

import app.shares.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('folders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=app.shares.models.generate_token, editable=False, max_length=64, unique=True)),
                ('permission_level', models.CharField(choices=[('read', '唯讀'), ('write', '可讀寫')], default='read', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='folders.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('file__isnull', False), ('folder__isnull', True)), models.Q(('file__isnull', True), ('folder__isnull', False)), _connector='OR'), name='share_exactly_one_target'),
        ),
    ]
