# Generated by Django 5.0.6 on 2026-08-09 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, help_text='null 代表這個檔案放在使用者的根目錄。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folders.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'folder', 'name'), name='unique_file_name_per_folder'),
        ),
    ]
