# Generated by Django 5.0.6 on 2026-08-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processing_status',
            field=models.CharField(choices=[('pending', '處理中'), ('done', '完成'), ('failed', '失敗')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
