# Generated by Django 5.0.6 on 2026-08-15 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_processing_status_file_thumbnail_key_and_more'),
        ('folders', '0002_remove_folder_unique_folder_name_per_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_file_name_per_folder',
        ),
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('owner', 'folder', 'name'), name='unique_file_name_per_folder'),
        ),
    ]
