# Generated by Django 5.0.6 on 2026-08-16 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_unique_file_name_per_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('size', models.BigIntegerField()),
                ('thumbnail_key', models.CharField(blank=True, default='', max_length=512)),
                ('processing_status', models.CharField(choices=[('pending', '處理中'), ('done', '完成'), ('failed', '失敗')], default='pending', max_length=20)),
                ('reference_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='file',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.RemoveField(
            model_name='file',
            name='storage_key',
        ),
        migrations.RemoveField(
            model_name='file',
            name='thumbnail_key',
        ),
        migrations.AddField(
            model_name='file',
            name='blob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.blob'),
        ),
    ]
