# Generated by Django 5.0.6 on 2026-08-16 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_blob_remove_file_hash_remove_file_processing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.blob'),
        ),
    ]
