# Generated by Django 5.0.6 on 2026-08-18 03:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_fileversion'),
        ('folders', '0002_remove_folder_unique_folder_name_per_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255)),
                ('total_size', models.BigIntegerField()),
                ('chunk_size', models.BigIntegerField(default=5242880)),
                ('total_chunks', models.PositiveIntegerField()),
                ('received_chunks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('uploading', '上傳中'), ('assembling', '組裝中'), ('completed', '完成'), ('failed', '失敗')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='folders.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
